### ISSUE TITLE
Problème avec l'API Freebox

### ISSUE THREAD

**Issue by justleska** [dathosim/HomeAssistant-Freebox-Pack-Securite#11]
Bonjour,

Quand je déploie mon flow Node-RED, j'ai ce message d'erreur:

```
Freebox mafreebox.freebox.fr:443/api_version error: AxiosError: Unsupported protocol mafreebox.freebox.fr:
    at dispatchHttpRequest (/config/node_modules/axios/lib/adapters/http.js:275:21)
    at /config/node_modules/axios/lib/adapters/http.js:152:5
    at new Promise (<anonymous>)
    at wrapAsync (/config/node_modules/axios/lib/adapters/http.js:132:10)
    at http (/config/node_modules/axios/lib/adapters/http.js:170:10)
    at Axios.dispatchRequest (/config/node_modules/axios/lib/core/dispatchRequest.js:51:10)
    at Axios._request (/config/node_modules/axios/lib/core/Axios.js:173:33)
    at Axios.request (/config/node_modules/axios/lib/core/Axios.js:40:25)
    at wrap (/config/node_modules/axios/lib/helpers/bind.js:5:15)
    at FreeboxServerNode.init (/config/node_modules/node-red-contrib-freebox/src/nodes/freebox-server/freebox-server.js:61:7)
    at Axios.request (/config/node_modules/axios/lib/core/Axios.js:45:41) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
   ...
```
![image](https://github.com/user-attachments/assets/9eeb664c-06f5-4c7c-a499-9c7cbd19b735)
![image](https://github.com/user-attachments/assets/6e9fb73f-d13b-45d4-976a-c3f46a459f21)

**Comment by justleska** [comment]
fix: 
![image](https://github.com/user-attachments/assets/c16d629a-c48a-43f8-8df2-a3464dde3da7)
